services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    ports:
      - "8070:8070"
    environment:
      - HOST_IP=host.docker.internal
    working_dir: "/app"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8070" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8070/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  agents:
    build:
      context: ./agents
      dockerfile: Dockerfile.agents
    ports:
      - "8080:8080"
    volumes:
      - "./logs:/app/logs"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - HOST_IP=host.docker.internal
    working_dir: "/app"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
      - "8090:8090"
    environment:
      - HOST_IP=host.docker.internal
    working_dir: "/app"
    command: ["streamlit", "run", "app.py", "--server.port", "8090"]

networks:
  default:
    name: financial-chatbot